// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlJDdSg2w7xg2zia6f2hMfCOTRJge9dm4',
    appId: '1:645943291914:web:6f325dbce88df2d445aff3',
    messagingSenderId: '645943291914',
    projectId: 'attendance-mangement-sys-1ec52',
    authDomain: 'attendance-mangement-sys-1ec52.firebaseapp.com',
    storageBucket: 'attendance-mangement-sys-1ec52.appspot.com',
    measurementId: 'G-CE0Y9ZR32T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpWLvCEiDTqvnvNfrJ1WHBVjNuLiLfSY',
    appId: '1:645943291914:android:735ca9f1b6fd096e45aff3',
    messagingSenderId: '645943291914',
    projectId: 'attendance-mangement-sys-1ec52',
    storageBucket: 'attendance-mangement-sys-1ec52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vJu10GR37odGPT9uwUmGgSMNRAJHo4o',
    appId: '1:645943291914:ios:38643c02e75b071545aff3',
    messagingSenderId: '645943291914',
    projectId: 'attendance-mangement-sys-1ec52',
    storageBucket: 'attendance-mangement-sys-1ec52.appspot.com',
    iosBundleId: 'com.example.studentManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vJu10GR37odGPT9uwUmGgSMNRAJHo4o',
    appId: '1:645943291914:ios:38643c02e75b071545aff3',
    messagingSenderId: '645943291914',
    projectId: 'attendance-mangement-sys-1ec52',
    storageBucket: 'attendance-mangement-sys-1ec52.appspot.com',
    iosBundleId: 'com.example.studentManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlJDdSg2w7xg2zia6f2hMfCOTRJge9dm4',
    appId: '1:645943291914:web:1a33fb1fc839a12045aff3',
    messagingSenderId: '645943291914',
    projectId: 'attendance-mangement-sys-1ec52',
    authDomain: 'attendance-mangement-sys-1ec52.firebaseapp.com',
    storageBucket: 'attendance-mangement-sys-1ec52.appspot.com',
    measurementId: 'G-PCCBHRTST6',
  );
}
